db_uri: mongodb://172.18.30.13/open5gs

#
# logger:
#
#  o Set OGS_LOG_INFO to all domain level
#   - If `level` is omitted, the default level is OGS_LOG_INFO)
#   - If `domain` is omitted, the all domain level is set from 'level'
#    (Nothing is needed)
#
#  o Set OGS_LOG_ERROR to all domain level
#   - `level` can be set with none, fatal, error, warn, info, debug, trace
#    level: error
#
#  o Set OGS_LOG_DEBUG to mme/emm domain level
#    level: debug
#    domain: mme,emm
#
#  o Set OGS_LOG_TRACE to all domain level
#    level: trace
#    domain: core,fd,pcrf,event,mem,sock
logger:
    file: /opt/LTE/log/pcrf/pcrf.log

pcrf:
#   freeDiameter: /opt/LTE//open5gs/etc/freeDiameter/pcrf.conf
    freeDiameter:
      identity: pcrf.epc.mncLTE_MNC.mccLTE_MCC.3gppnetwork.org
      realm: epc.mncLTE_MNC.mccLTE_MCC.3gppnetwork.org
      port: 3868
#     sec_port: 5868
      listen_on: 172.18.30.8
      load_extension:
        - module: /opt/LTE//open5gs/lib/x86_64-linux-gnu/freeDiameter/dbg_msg_dumps.fdx
          conf: 0x8888
        - module: /opt/LTE//open5gs/lib/x86_64-linux-gnu/freeDiameter/dict_rfc5777.fdx
        - module: /opt/LTE//open5gs/lib/x86_64-linux-gnu/freeDiameter/dict_mip6i.fdx
        - module: /opt/LTE//open5gs/lib/x86_64-linux-gnu/freeDiameter/dict_nasreq.fdx
        - module: /opt/LTE//open5gs/lib/x86_64-linux-gnu/freeDiameter/dict_nas_mipv6.fdx
        - module: /opt/LTE//open5gs/lib/x86_64-linux-gnu/freeDiameter/dict_dcca.fdx
        - module: /opt/LTE//open5gs/lib/x86_64-linux-gnu/freeDiameter/dict_dcca_3gpp.fdx
      connect:
        - identity: pgw.epc.mncLTE_MNC.mccLTE_MCC.3gppnetwork.org
          addr: 172.18.30.6
          port: 3868
        - identity: pcscf.ims.mncLTE_MNC.mccLTE_MCC.3gppnetwork.org
          addr: 172.18.30.11
          port: 3871


# parameter:
#
#  o Number of output streams per SCTP associations.
#      sctp_streams: 30
#
#  o Disable use of IPv4 addresses (only IPv6)
#      no_ipv4: true
#
#  o Disable use of IPv6 addresses (only IPv4)
#      no_ipv6: true
#
#  o Prefer IPv4 instead of IPv6 for estabishing new GTP connections.
#      prefer_ipv4: true
#
#  o Enable Multicast traffic to the UE
#      multicast: true
#
#  o Disable Stateless Address Autoconfiguration for IPv6
#      no_slaac: true
#
parameter:

#
# max:
#
# o Maximum Number of SGW per MME
#    sgw: 32
# o Maximum Number of PGW per MME
#    pgw: 32
# o Maximum Number of VLR per MME
#    vlr: 32
# o Maximum Number of eNodeB per MME
#    enb: 32
# o Maximum Number of UE per eNodeB
#    ue: 128
#
max:

#
# pool:
#
# o The Number of Default Memory Pool Size
#
#   - Pool-size 128         => 8192 Number
#   - Pool-size 256         => 4096 Number
#   - Pool-size 512         => 2048 Number
#   - Pool-size 1024        => 1024 Number
#   - Pool-size 2048        => 512 Number
#   - Pool-size 8192        => 128 Number
#   - Pool-size 1024*1024   => 8 Number
#
#    128:  8192
#    256:  4096
#    512:  2048
#    1024: 1024
#    2048: 512
#    8192: 128
#    big:  8
#
# o Memory of Packet Buffering in SGW
#   - Maximum Number of packet(SDU size = 8Kbytes) pool in SGW
#   - SGW Memory Usage : 65536 * 8Kbytes = 512Mbytes
#
#   packet: 65536
#
pool:
